diff --git a/Makefile b/Makefile
index d17cfca..d2e232a 100644
--- a/Makefile
+++ b/Makefile
@@ -26,7 +26,7 @@ TREE_DEST=tree
 DESTDIR=${PREFIX}/bin
 MAN=tree.1
 # Probably needs to be ${PREFIX}/share/man for most systems now
-MANDIR=${PREFIX}/man
+MANDIR=${PREFIX}/share/man
 OBJS=tree.o list.o hash.o color.o file.o filter.o info.o unix.o xml.o json.o html.o strverscmp.o

 # Uncomment options below for your particular OS:
@@ -94,7 +94,7 @@ CFLAGS+=-ggdb -std=c11 -pedantic -Wall -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS
 all:	tree
 
 tree:	$(OBJS)
-	$(CC) $(LDFLAGS) -o $(TREE_DEST) $(OBJS)
+	$(CC) $(LDFLAGS) -o $(TREE_DEST) $(OBJS) $(LIBS)
 
 $(OBJS): %.o:	%.c tree.h
 	$(CC) $(CFLAGS) -c -o $@ $<
